import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Nunito({
  subsets: ['latin'],
  weight: ['400', '700'], // kerakli og‘irliklar
  variable: '--Family-Nunito', 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-800`}
      >
        {children}
      </body>
    </html>
  );
}
